### ISSUE TITLE
Crashes if --num_iterations 2

### ISSUE THREAD

**Issue by sdanzige** [baliga-lab/cmonkey2#42]
sdanziger@sdanziger-lx:~/Work/BSCM/cmonkey-python$ ./cmonkey.py --organism hal --ratios example_data/hal/halo_ratios5.tsv --num_iterations 2
2015-02-04 17:20:19 INFO     checking MEME...
2015-02-04 17:20:19 INFO     Input matrix has # rows: 428, # columns: 5
2015-02-04 17:20:19 INFO     # clusters/row: 2
2015-02-04 17:20:19 INFO     # clusters/column: 29
2015-02-04 17:20:19 INFO     # CLUSTERS: 43
2015-02-04 17:20:19 INFO     use operons: 1
2015-02-04 17:20:19 INFO     using MEME version 4.9.1
2015-02-04 17:20:21 INFO     attempting automatic download of operons from Microbes Online
2015-02-04 17:20:21 INFO     NCBI CODE IS: 64091
2015-02-04 17:20:21 INFO     Automatically using STRING file in 'cache/64091.gz'
2015-02-04 17:20:21 INFO     RSAT - get_directory()
2015-02-04 17:20:32 INFO     KEGG = 'Halobacterium sp. NRC-1' -> RSAT = 'Halobacterium_sp'
2015-02-04 17:20:32 INFO     Creating networks...
2015-02-04 17:20:32 INFO     stringdb.read_edges2()
2015-02-04 17:20:33 INFO     stringdb.read_edges2(), 8514 edges read, 227014 edges ignored
2015-02-04 17:20:33 INFO     MicrobesOnline - make_network()
2015-02-04 17:20:33 INFO     MicrobesOnline.get_operon_predictions_for(64091)
2015-02-04 17:20:33 INFO     502 prediction pairs read
2015-02-04 17:20:33 INFO     RSAT - get_features(Halobacterium_sp)
2015-02-04 17:20:33 INFO     331 operons created
2015-02-04 17:20:33 WARNING  dropped operon from network (max_operon_size exceeded): ['VNG1688C', 'VNG1689G', 'VNG1690G', 'VNG1691G', 'VNG1692G', 'VNG1693G', 'VNG1695G', 'VNG1697G', 'VNG1698G', 'VNG1699C', 'VNG1700G', 'VNG1701G', 'VNG1702G', 'VNG1703G', 'VNG1705G', 'VNG1706G', 'VNG1707G', 'VNG1709G', 'VNG1711G', 'VNG1713G', 'VNG1714G', 'VNG1715G', 'VNG1716G', 'VNG1718G', 'VNG1719G']
2015-02-04 17:20:33 INFO     766 edges computed
2015-02-04 17:20:33 INFO     Finished creating networks.
2015-02-04 17:20:33 INFO     MicrobesOnline.get_operon_predictions_for(64091)
2015-02-04 17:20:33 INFO     502 prediction pairs read
2015-02-04 17:20:33 INFO     RSAT - get_features(Halobacterium_sp)
2015-02-04 17:20:33 INFO     331 operons created
2015-02-04 17:20:34 INFO     RSAT - get_features(Halobacterium_sp)
2015-02-04 17:20:34 INFO     RSAT - get_contig_sequence(Halobacterium_sp, NC_002607.1)
2015-02-04 17:20:34 INFO     RSAT - get_contig_sequence(Halobacterium_sp, NC_002608.1)
2015-02-04 17:20:35 INFO     RSAT - get_features(Halobacterium_sp)
2015-02-04 17:20:35 INFO     RSAT - get_contig_sequence(Halobacterium_sp, NC_002607.1)
2015-02-04 17:20:35 INFO     RSAT - get_contig_sequence(Halobacterium_sp, NC_002608.1)
2015-02-04 17:20:35 WARNING  25 genes not found in synonyms.
2015-02-04 17:20:35 INFO     cmonkey_run config_params:
2015-02-04 17:20:35 INFO     memb.max_cluster_rows_allowed=70
2015-02-04 17:20:35 INFO     MEME={'background_order': '3', 'use_revcomp': 'True', 'arg_mod': 'zoops', 'schedule': 1,100, 'max_width': '24', 'nmotifs_rvec': 'c(rep(1, num_iterations/3), rep(2, num_iterations/3))', 'version': '4.9.1', 'global_background': 'True'}
2015-02-04 17:20:35 INFO     rsat_dir=None
2015-02-04 17:20:35 INFO     Rows={'scaling': ('scaling_const', 0.3), 'schedule': 1,2}
2015-02-04 17:20:35 INFO     nomotifs=False
2015-02-04 17:20:35 INFO     memb.clusters_per_row=2
2015-02-04 17:20:35 INFO     string_file=cache/64091.gz
2015-02-04 17:20:35 INFO     minimize_io=False
2015-02-04 17:20:35 INFO     fasta_file=None
2015-02-04 17:20:35 INFO     memb.max_changes_per_row=1
2015-02-04 17:20:35 INFO     organism_code=hal
2015-02-04 17:20:35 INFO     rsat_organism=None
2015-02-04 17:20:35 INFO     remap_network_nodes=False
2015-02-04 17:20:35 INFO     operon_file=None
2015-02-04 17:20:35 INFO     Motifs={'scaling': ('scaling_rvec', 'c(rep(1e-5, 100), seq(1e-5, 1, length=num_iterations*3/4))'), 'sequence_types': 'upstream', 'schedule': 2,10}
2015-02-04 17:20:35 INFO     result_freq=10
2015-02-04 17:20:35 INFO     Weeder={'schedule': 1,100, 'top': '50', 'analysis': 'small', 'nmotifs_rvec': 'c(rep(1, num_iterations/3), rep(2, num_iterations/3))', 'freqfile_dir': '', 'global_background': 'True', 'orgcode': ''}
2015-02-04 17:20:35 INFO     tmp_dir=
2015-02-04 17:20:35 INFO     sequence_types=['upstream']
2015-02-04 17:20:35 INFO     memb.max_changes_per_col=5
2015-02-04 17:20:35 INFO     logfile=None
2015-02-04 17:20:35 INFO     quantile_normalize=False
2015-02-04 17:20:35 INFO     checkratios=False
2015-02-04 17:20:35 INFO     memb.prob_col_change=1.0
2015-02-04 17:20:35 INFO     ncbi_code=64091
2015-02-04 17:20:35 INFO     debug_freq=50
2015-02-04 17:20:35 INFO     memb.clusters_per_col=29
2015-02-04 17:20:35 INFO     memb.min_cluster_rows_allowed=3
2015-02-04 17:20:35 INFO     case_sensitive=False
2015-02-04 17:20:35 INFO     pipeline_file=
2015-02-04 17:20:35 INFO     normalize_ratios=True
2015-02-04 17:20:35 INFO     output_dir=out
2015-02-04 17:20:35 INFO     postadjust=True
2015-02-04 17:20:35 INFO     num_clusters=43
2015-02-04 17:20:35 INFO     start_iteration=1
2015-02-04 17:20:35 INFO     command_line=./cmonkey.py --organism hal --ratios example_data/hal/halo_ratios5.tsv --num_iterations 2
2015-02-04 17:20:35 INFO     use_BSCM=False
2015-02-04 17:20:35 INFO     stats_freq=10
2015-02-04 17:20:35 INFO     SequenceType-upstream={'search_distance': '-20,150', 'scan_distance': '-30,250'}
2015-02-04 17:20:35 INFO     random_seed=1465044708
2015-02-04 17:20:35 INFO     resume=False
2015-02-04 17:20:35 INFO     use_string=True
2015-02-04 17:20:35 INFO     nonetworks=False
2015-02-04 17:20:35 INFO     rsat_base_url=http://embnet.ccg.unam.mx/rsa-tools
2015-02-04 17:20:35 INFO     out_database=out/cmonkey_run.db
2015-02-04 17:20:35 INFO     ratios_file=example_data/hal/halo_ratios5.tsv
2015-02-04 17:20:35 INFO     cache_dir=cache
2015-02-04 17:20:35 INFO     search_distances={'upstream': (-20, 150)}
2015-02-04 17:20:35 INFO     memb.prob_row_change=0.5
2015-02-04 17:20:35 INFO     add_fuzz=rows
2015-02-04 17:20:35 INFO     Columns={'schedule': 1,5}
2015-02-04 17:20:35 INFO     log_subresults=True
2015-02-04 17:20:35 INFO     synonym_file=None
2015-02-04 17:20:35 INFO     rsat_features=feature
2015-02-04 17:20:35 INFO     pipeline={u'row-scoring': {u'function': {u'class': u'ScoringFunctionCombiner', u'module': u'cmonkey.scoring'}, u'args': {u'functions': [{u'function': {u'class': u'RowScoringFunction', u'module': u'cmonkey.microarray'}, u'id': u'Rows'}, {u'function': {u'class': u'ScoringFunction', u'module': u'cmonkey.network'}, u'id': u'Networks'}, {u'function': {u'class': u'MemeScoringFunction', u'module': u'cmonkey.motif'}, u'id': u'Motifs'}]}, u'id': u'combiner'}, u'column-scoring': {u'function': {u'class': u'ColumnScoringFunction', u'module': u'cmonkey.scoring'}, u'id': u'Columns'}}
2015-02-04 17:20:35 INFO     num_iterations=2
2015-02-04 17:20:35 INFO     num_cores=None
2015-02-04 17:20:35 INFO     dbfile_name=cmonkey_run.db
2015-02-04 17:20:35 INFO     Networks={'scaling': ('scaling_rvec', 'seq(1e-5, 0.5, length=num_iterations*3/4)'), 'schedule': 1,7}
2015-02-04 17:20:35 INFO     use_operons=True
2015-02-04 17:20:35 INFO     scan_distances={'upstream': (-30, 250)}
2015-02-04 17:20:35 INFO     debug=set([])
2015-02-04 17:20:35 INFO     multiprocessing=True
2015-02-04 17:20:35 INFO     interactive=False
2015-02-04 17:20:35 INFO     Iteration # 1
Traceback (most recent call last):
  File "./cmonkey.py", line 37, in <module>
    cmonkey_run.run()
  File "/autoxfs/aitchison/yeast/Aitchison lab/sdanziger/Work/BSCM/cmonkey-python/cmonkey/cmonkey_run.py", line 497, in run
    self.run_iterations()
  File "/autoxfs/aitchison/yeast/Aitchison lab/sdanziger/Work/BSCM/cmonkey-python/cmonkey/cmonkey_run.py", line 729, in run_iterations
    self.run_iteration(iteration)
  File "/autoxfs/aitchison/yeast/Aitchison lab/sdanziger/Work/BSCM/cmonkey-python/cmonkey/cmonkey_run.py", line 663, in run_iteration
    rscores = self.row_scoring.compute(iteration_result)
  File "/autoxfs/aitchison/yeast/Aitchison lab/sdanziger/Work/BSCM/cmonkey-python/cmonkey/scoring.py", line 470, in compute
    matrix = scoring_function.compute(iteration_result, reference_matrix)
  File "/autoxfs/aitchison/yeast/Aitchison lab/sdanziger/Work/BSCM/cmonkey-python/cmonkey/motif.py", line 212, in compute
    return self.__compute(iteration_result, False, ref_matrix)
  File "/autoxfs/aitchison/yeast/Aitchison lab/sdanziger/Work/BSCM/cmonkey-python/cmonkey/motif.py", line 237, in __compute
    num_motifs = int(self.num_motif_func(iteration))
  File "/autoxfs/aitchison/yeast/Aitchison lab/sdanziger/Work/BSCM/cmonkey-python/cmonkey/util.py", line 449, in scale
    return rvec[-1]
  File "/usr/local/lib/python2.7/dist-packages/rpy2/robjects/vectors.py", line 244, in __getitem__
    res = super(Vector, self).__getitem__(i)
IndexError: Index out of range.

**Comment by weiju** [comment]
The problem is that for 2 iterations, you need to define a different nmotifs_rvec function
The setting defined in default.ini is:

[MEME]
nmotifs_rvec=c(rep(1, num_iterations/3), rep(2, num_iterations/3))

which effectively means, this will only work from 3 iterations. Admittedly, such a large number of iterations is a rather unlikely case and only intended for testing purposes.
