### ISSUE TITLE
Problem with Aspergillus

### ISSUE THREAD

**Issue by IvanV87** [baliga-lab/cmonkey2#49]
Hi am attempting to use cmonkey on several Aspergillus species (niger, terreus, and fumigatus), for now im using expression data from Aspergillus fumigatus af293, however when i try to use cmonkey2 this is the error that I get:

:~/cmonkey2$ ./cmonkey.py --ratios /home/ivanvaldes/cmonkey2/aspdata/matrixsinnorm.txt --organism afm
2015-05-22 16:26:58 INFO     checking MEME...
2015-05-22 16:26:58 INFO     Input matrix has # rows: 967, # columns: 25
2015-05-22 16:26:58 INFO     # clusters/row: 2
2015-05-22 16:26:58 INFO     # clusters/column: 65
2015-05-22 16:26:58 INFO     # CLUSTERS: 97
2015-05-22 16:26:58 INFO     use operons: 1
2015-05-22 16:26:58 INFO     using MEME version 4.3.0
2015-05-22 16:26:58 INFO     attempting automatic download of operons from Microbes Online
2015-05-22 16:26:58 INFO     NCBI CODE IS: 330879
2015-05-22 16:26:58 INFO     Automatically using STRING file in 'cache/330879.gz'
Traceback (most recent call last):
  File "./cmonkey.py", line 36, in <module>
    cmonkey_run.run()
  File "/home/ivanvaldes/cmonkey2/cmonkey/cmonkey_run.py", line 505, in run
    self.prepare_run()
  File "/home/ivanvaldes/cmonkey2/cmonkey/cmonkey_run.py", line 467, in prepare_run
    thesaurus = self.organism().thesaurus()
  File "/home/ivanvaldes/cmonkey2/cmonkey/cmonkey_run.py", line 226, in organism
    self.__organism = self.make_organism()
  File "/home/ivanvaldes/cmonkey2/cmonkey/cmonkey_run.py", line 301, in make_organism
    util.get_url_cached(url, stringfile)
  File "/home/ivanvaldes/cmonkey2/cmonkey/util.py", line 275, in get_url_cached
    CMonkeyURLopener().retrieve(url, cache_filename)
  File "/usr/lib/python2.7/urllib.py", line 240, in retrieve
    fp = self.open(url, data)
  File "/usr/lib/python2.7/urllib.py", line 208, in open
    return getattr(self, name)(url)
  File "/usr/lib/python2.7/urllib.py", line 359, in open_http
    return self.http_error(url, fp, errcode, errmsg, headers)
  File "/usr/lib/python2.7/urllib.py", line 376, in http_error
    return self.http_error_default(url, fp, errcode, errmsg, headers)
  File "/home/ivanvaldes/cmonkey2/cmonkey/util.py", line 245, in http_error_default
    raise DocumentNotFound(url)
cmonkey.util.DocumentNotFound: //networks.systemsbiology.net/string9/330879.gz

It seams that the NCBI code of the Aspergilli species does not correspond to the code in the string database.

according to to string database
## taxon_id STRING_type STRING_name_compact official_name_NCBI

5057    periphery   Aspergillus clavatus    Aspergillus clavatus
5059    periphery   Aspergillus flavus  Aspergillus flavus
5061    periphery   Aspergillus niger   Aspergillus niger
5062    periphery   Aspergillus oryzae  Aspergillus oryzae
5085    core    Aspergillus fumigatus   Aspergillus fumigatus

According to NCBI taxonomy database:

-Aspergillus clavatus
 Taxonomy ID: 5057
-Aspergillus flavus
 Taxonomy ID: 5059
-Aspergillus fumigatus Af293
  Taxonomy ID: 330879
-Aspergillus oryzae
Taxonomy ID: 5062
-Aspergillus niger
Taxonomy ID: 5061

Hope that you could help me with this.

Regards

**Comment by weiju** [comment]
Hi, it looks like STRING has Aspergillus fumigatus stored under NCBI id 5085, which is available. Could you please try if it works for you using --ncbi_code 5085 ?

**Comment by IvanV87** [comment]
I tried that , the program runs but i cannot look up for the MEME results or the STRING results.
