### ISSUE TITLE
MAST error in attempted human run

### ISSUE THREAD

**Issue by cfbuenabadn** [baliga-lab/cmonkey2#54]
Hello, I am trying to run cMonkey2 on human data. At first it seems to be working just fine, but after a while it crashes and I get the following error:

```

2016-08-10 22:43:23 INFO     running meme/mast on cluster 299, # sequences: 3
2016-08-10 22:43:25 WARNING  there is an exception thrown in MAST: FATAL: The motif selection criteria is too strict and all motifs were excluded.

, (meme file: '/tmp/meme.out.UZ2NtV', dbfile: '/tmp/memeseqsfpGxdA', bgfile: '/tmp/memebgJ_w7m_')
2016-08-10 22:43:25 INFO     running meme/mast on cluster 200, # sequences: 2
Traceback (most recent call last):
  File "cmonkey.py", line 36, in <module>
    cmonkey_run.run()
  File "/mnt/lareaulab/cfbuenabadn/programs/cmonkey2/cmonkey/cmonkey_run.py", line 516, in run
    self.run_iterations()
  File "/mnt/lareaulab/cfbuenabadn/programs/cmonkey2/cmonkey/cmonkey_run.py", line 774, in run_iterations
    self.run_iteration(iteration, force=force)
  File "/mnt/lareaulab/cfbuenabadn/programs/cmonkey2/cmonkey/cmonkey_run.py", line 704, in run_iteration
    rscores = self.row_scoring.compute(iteration_result)
  File "/mnt/lareaulab/cfbuenabadn/programs/cmonkey2/cmonkey/scoring.py", line 480, in compute
    matrix = scoring_function.compute(iteration_result, reference_matrix)
  File "/mnt/lareaulab/cfbuenabadn/programs/cmonkey2/cmonkey/motif.py", line 224, in compute
    return self.__compute(iteration_result, False, ref_matrix)
  File "/mnt/lareaulab/cfbuenabadn/programs/cmonkey2/cmonkey/motif.py", line 252, in __compute
    num_motifs, force)
  File "/mnt/lareaulab/cfbuenabadn/programs/cmonkey2/cmonkey/motif.py", line 373, in compute_pvalues  
    results = pool.map(compute_cluster_score, params.values())
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
AttributeError: 'NoneType' object has no attribute 'replace'


```

Maybe I could try to work with --nomotifs, but I am curious on what is causing this error.

**Comment by prashantkum7** [comment]
Hi,

I am also getting the same error. Could you help me with this?

Thanks

**Comment by weiju** [comment]
which version of MEME are you using ?

**Comment by weiju** [comment]
This is identical to issue #51
